Adding TASK_BULK_MKDIR_THRESHOLD as configurable Fixes #2089
radical-cybertools/radical.pilot pull request #2726
Opened 2022-10-07 19:34 UTC by kartikmodi

2022-10-07 19:36 UTC, andre-merzky commented on src/radical/pilot/configs/tmgr_default.json
> +    #
This line is probably not needed?

2022-10-12 17:02 UTC, kartikmodi commented
@andre-merzky Please review. I think there was one more comment from you in the call, which I kind of forget. I did 2 changes.

2022-10-16 21:32 UTC, andre-merzky requested changes
Looks good to me - but left a comment on the variable name.

2022-10-16 21:32 UTC, andre-merzky commented on src/radical/pilot/tmgr/staging_input/default.py
> +                     TASK_BULK_MKDIR_THRESHOLD)
class member variables should be lower case and short (only constants are all uppercase).  Also, private variables should have a leading underscrore. Maybe use `self._mkdir_threshold`?

2022-10-18 07:54 UTC, andre-merzky approved these changes
Thanks,    LGTM

2022-10-24 00:36 UTC, merged