fix docs #3254
radical-cybertools/radical.pilot pull request #3256
Opened 2024-11-13 12:28 UTC by AymenFJA

This addresses to [#3254](https://github.com/radical-cybertools/radical.pilot/issues/3254)

2024-11-13 17:02 UTC, andre-merzky approved these changes
LGTM!

2024-11-13 17:05 UTC, andre-merzky commented on docs/source/tutorials/submission.ipynb
>      "           'access_schema': 'ssh'\n",
This line misses a comma, causing the NB to fail.

2024-11-13 17:05 UTC, andre-merzky requested changes
Left a minor change request

2024-11-13 18:28 UTC, mtitov commented
@andre-merzky @AymenFJA have a general proposal to rewrite this section/tutorial:
1. our focus is a "local" submission - either from the login node or from the compute node (i.e., inside the batch job, using interactive job or batch script). Thus, we don't talk about `access_schema` parameters here at all, because it is set by default. We can give examples of how to get interactive job or write a batch script (while considering that the RP pilot description is not anyhow different for these examples), but we should make a note that user is required to refer to the corresponding platform's user guide to follow their instructions.
2. "remote" submission, which is **optional** and **only** if platform supports it. If it is the case, then user need to have a corresponding configuration within the resource config for that platform, and the name for that set of config parameters (e.g., `ssh`, `gsissh`, etc.) should be used in the `access_schema` for `PilotDescription`.

Thus, this section is about submission within the platform, the second part is optional

2024-12-02 07:39 UTC, andre-merzky approved these changes
LGTM - thanks!

2024-12-03 22:29 UTC, mtitov approved these changes
Let's merge it, and further updates will be in a separate PR. These changes LGTM! Thanks!

2024-12-04 13:05 UTC, merged